### ISSUE TITLE
Vite dev server with netlify dev support

### ISSUE THREAD

**Issue by web2033** [web2033/vite-vue3-tailwind-starter#238]
```toml
# netlify.toml
[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run build'
environment = {NODE_VERSION = '16'}
publish = 'dist'

[dev]
autoLaunch = false
```

```js
// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  server: {
    open: true,
    proxy: {
      '/api': {
        target: 'http://localhost:8888/.netlify/functions',
        changeOrigin: true,
        rewrite: path => path.replace(/^\/api/, ''),
      },
    },
  },
})
```
Then run the first command (Netlify will launch Vite dev server automatically if the second command is present):
```json
  "scripts": {
    "netlify": "netlify dev",
    "dev": "vite",
    "build": "vite build"
  },
```

Now, you can create a function like 
`netlify/functions/hello.js`
and call it from your .vue component like 
`fetch('/api/hello)`
